### ISSUE TITLE
Supports only single instance per page

### ISSUE THREAD

**Issue by TheDigitalOrchard** [tdsymonds/simple-flow#1]
Seems that SimpleFlow does not allow joining together multiple groups of objects. Only the last one that's listed (in terms of code execution) takes effect; the previous are not drawn.

Is this a known issue? Is there a workaround?

I tested this by assigning different class names to groups of objects and calling SimpleFlow() for each class name. No joy.

**Comment by tdsymonds** [comment]
Thanks for pointing this out. You were right, there was a bug that was preventing multiple instances of SimpleFlow being created on a page.

This issue has now been resolved in release 1.1.0.

I've updated the demo to show how this can be done and created a new Codepen: 

https://codepen.io/tdsymonds/pen/qpwagR

You'll need to create a new canvas, which you'll pass into the SimpleFlow, eg:
```
$('.object2').SimpleFlow({
      canvasElm: '.canvas2'
});
```
And you'll need to add your own styling:
```
.canvas2{
  position:relative;
  padding: 0 50px;
}

/* How you style the object is optional, this is an example */
.object2{
  background: #d77e97;
  height: 100px;
  width:100%;
  margin: 15px 0;
  display:table;
  color: #fff;
}
```

Thanks
